### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by asywalulfikri** [raitucarp/paratree#1]
kok ga bisa di jalanin di Android Studio ya ?

**Comment by raitucarp** [comment]
This is for javascript/node.js not for Java/Kotlin. The documentation is not clear right now, but I promise to write complete documentation in the near future.

If you are willing to port paratree to Java or JVM based languages such as Kotlin or Scala, then go on. I also want to do the same thing in the future (porting to golang / kotlin maybe).

However, you can still use this module in react-native without any problems.

I close this issue as this is inappropriate. Thanks

**Comment by asywalulfikri** [comment]
wkwkkw. becanda om ✌️. ampun om
